### ISSUE TITLE
Assemble the `Officer` page

### ISSUE THREAD

**Issue by srirag-vuppala** [CSSGCalPoly/club-website#69]
Problem
---
Once all of the components are completed for the Officer page, they need to be placed on a single page and tested to ensure there are no conflicts between them. 

Do This
---

This page will be built using the following components:
- The Officer banner #43   
- The Officer Cards Layout Component #68 

Assemble the page as shown in the [figma ](https://www.figma.com/file/i3QlbebnZaaKwrQP2x5qe3/Final-Website-Design?node-id=0%3A1).
<img width="307" alt="Screen Shot 2021-04-15 at 3 05 06 PM" src="https://user-images.githubusercontent.com/23414761/114944199-023fff00-9dfc-11eb-8caf-b96aeac6a606.png">

These components have not been tested while interacting together. Once the page is assembled be sure to thoroughly test it! Make sure to include a list of any problems in the pull request along with screenshots.  

- Test it on different screen sizes
- Reference the [Figma](https://www.figma.com/file/i3QlbebnZaaKwrQP2x5qe3/Final-Website-Design?node-id=0%3A1) to verify everything looks correct.

Notes
---
- The page background color must be set to white to ensure contrast for the wave of the banner
- Remember to test the page with different screen sizes
 - If there are any issues with the underlying components write an include a list of any problems in the pull request along with screenshots.

**Comment by adellevo** [comment]
The grid looks really clean, and it wraps nicely when I resize the screen! Random side note, but the look of the non-encapsulated card is starting to grow on me lol. Some things related to the officer page in general and not really the layout:

* officer names / LinkedIn links need to be replaced
* the Linkedin logo doesn't quite align with the right corner 
<img width="212" alt="Screen Shot 2021-08-17 at 9 05 32 PM" src="https://user-images.githubusercontent.com/22452107/129835237-245017d5-4f84-450d-85ed-afbc4df62763.png">
* the background shapes in the banner go out of bounds at certain viewport widths
<img width="361" alt="Screen Shot 2021-08-17 at 9 05 46 PM" src="https://user-images.githubusercontent.com/22452107/129835259-ca78dec0-8ef5-4691-adc9-e6b5f1669cc4.png">
* maybe decrease the spacing between the rows to match the amount of space between the bottom of the banner and the top row
<img width="425" alt="Screen Shot 2021-08-17 at 9 05 19 PM" src="https://user-images.githubusercontent.com/22452107/129835229-4149600e-fc3f-4926-9f45-e792482a91fe.png">

If you want to merge now, we could just leave these 'till the end though — was thinking it'd be easier to take care of now, but it's your call haha
